apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: subdomain-4cc090d2-2c86-4ab5-881a-18d2aa37873a
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/LynaSovann/subdomain-4cc090d2-2c86-4ab5-881a-18d2aa37873a.git
    targetRevision: main
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: subdomain-4cc090d2-2c86-4ab5-881a-18d2aa37873a
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 5
